name: Trigger Repo B Workflow

on:
  push:
    branches:
      - main # Adjust this to your main branch name or desired trigger branch

jobs:
  trigger-repo-b-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo B Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: ydahal1/solutions-lab-personal # Update with your Repo B details
          event-type: content-updated
